---
version: "3.3"

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  seed-db:
    image: migrate/migrate
    volumes:
      - ./db/migrations:/migrations
    entrypoint: /bin/sh -c 'sleep 5 && migrate -path=/migrations/ -database "mongodb://root:example@mongo:27017/main?authSource=admin" up'
    depends_on:
      - "mongo"
      
  sigma-backend:
    build: backend
    ports:
      - 8080:8080
    depends_on:
      - "db"

  sigma-frontend:
    build: frontend
    ports:
      - 5000:5000